JavaScriptについてまとめた
chiharu1990/tspractice pull request #1
Opened 2024-09-19 07:30 UTC by chiharu1990

## 概要

- JavaScriptの色々な用語について調べてまとめた

2024-09-19 08:47 UTC, o765cGxHQk requested changes
お姑しましたのでご確認ください！

このドキュメントを充実させる形で、
用語理解を深めていっていただければと思います💪

2024-09-19 08:47 UTC, o765cGxHQk commented on note/README.md
> +Node.js でも動く。
> Node.js でも動く。 

これは何故ですか？

2024-09-19 08:47 UTC, o765cGxHQk commented on note/README.md
> +Web ブラウザやサーバー上で JavaScript コードを実行するためのソフトウェアスタック
> ソフトウェアスタック 

ソフトウェアスタック ということは何と何で構成されていますか？

2024-09-19 08:47 UTC, o765cGxHQk commented on note/README.md
> +それを実行するプログラムのことをコンパイラーという（gulp など）
> それを実行するプログラムのことをコンパイラーという（gulp など）  

gulpは本当にコンパイラーですか？

2024-09-19 08:47 UTC, o765cGxHQk commented on note/README.md
> +トランスパイルも似たような意味合いであるが、 最新のコードを古い構文を使って書き換えることをいう
> 最新のコードを古い構文を使って書き換えることをいう 

古い構文にすることをトランスパイルと呼びますか？
また、古い構文にすることでどんなメリットがありますか？

2024-09-19 08:47 UTC, o765cGxHQk commented on note/README.md
> +連携するシステム全般のことを言うのかな・・・
フロントエンドのエコシステムのうち、具体例を4つ以上挙げてください。

例.
リンター

2024-09-19 08:47 UTC, o765cGxHQk commented on note/README.md
> +Node.js、DENO、BUN などがある。
> Node.js、DENO、BUN などがある。  

具体例あげてくれるの良いと思います🙆‍♀️

2024-09-19 15:28 UTC, chiharu1990 commented on note/README.md
> +Web ブラウザやサーバー上で JavaScript コードを実行するためのソフトウェアスタック
@o765cGxHQk 
こちら追記しました！
f11e41954fab8c0466f4697bbb1bc4675a8e727c

2024-09-19 15:29 UTC, chiharu1990 commented on note/README.md
> +それを実行するプログラムのことをコンパイラーという（gulp など）
@o765cGxHQk 
こちらも追記しました！
f11e41954fab8c0466f4697bbb1bc4675a8e727c

2024-09-19 15:29 UTC, chiharu1990 commented on note/README.md
> +トランスパイルも似たような意味合いであるが、 最新のコードを古い構文を使って書き換えることをいう
@o765cGxHQk
こちらも追記しました！
https://github.com/chiharu1990/tspractice/commit/f11e41954fab8c0466f4697bbb1bc4675a8e727c

2024-09-19 15:29 UTC, chiharu1990 commented on note/README.md
> +連携するシステム全般のことを言うのかな・・・
@o765cGxHQk
こちらも追記しました！
https://github.com/chiharu1990/tspractice/commit/f11e41954fab8c0466f4697bbb1bc4675a8e727c

2024-09-19 15:30 UTC, chiharu1990 commented
@o765cGxHQk 
質問いただいていた内容をもう少し調べ直して追記・修正しました！
一つ一つ分けてコミットした方が良かったですかね・・・？
ご確認お願いいたします！

2024-09-20 01:27 UTC, o765cGxHQk requested changes
修正ありがとうございます！
コメントしました💭

2024-09-20 01:27 UTC, o765cGxHQk commented on note/README.md
> +通常、JavaScript はブラウザ上で動作するプログラミング言語で、OS の機能にアクセスできないが、Node.js は OS の機能にアクセスするプログラムを組むことができる。
> Web ブラウザの中で動くプログラミング言語。Web サイト上で操作をしたら表示が書き変わったり、Web サイトのサーバーと通信してデータを取得したりすることができる。  
> Node.js でも動く。  
> なぜ、Node.js でも動くのか？  
> → Node.js は JavaScript の実行環境だから・・・？  
> 通常、JavaScript はブラウザ上で動作するプログラミング言語で、OS の機能にアクセスできないが、Node.js は OS の機能にアクセスするプログラムを組むことができる。

この段落で文章は繋がっているでしょうか？
「JavaScriptはブラウザで動く」が、「Node.jsはOSにアクセスできる」と読めます。
JavaScriptとNode.jsは並列に書くべきものでしょうか・・？
あとで書いてもらっているランタイムの項目と合わせて考えてみてください。

> Node.js は JavaScript の実行環境だから・・・？ 

ここは合っています！🙆‍♀️
おっしゃるとおり実行環境ですね 👍

2024-09-20 01:27 UTC, o765cGxHQk commented on note/README.md
> +→ JavaScript 実行エンジン（V8 など）と実行基盤（Node.js など）
> ソフトウェアスタックの構成は？  
> → JavaScript 実行エンジン（V8 など）と実行基盤（Node.js など）

構成内容の厳密性を求めているわけではないのですが、ランタイムシステム（Node.js）の中にランタイムエンジン（V8）があり、ランタイムライブラリを包括している、といった書き方の方がよいと思いました。

2024-09-20 01:27 UTC, o765cGxHQk commented on note/README.md
> +ブラウザは JavaScript 実行エンジンがあって（Chrome なら V8,FireFox なら SpiderMonkey など）、これらの実行エンジンにモジュールシステムや API などを加えた JavaScript の実行基盤が JavaScript ランタイム
>モジュールシステムや API

ここで出てくるAPIとはなんですか？👿 
ブラウザにはモジュールシステムやAPIはありませんか？

2024-09-20 01:27 UTC, o765cGxHQk commented on note/README.md
> +→ gulp はタスクランナーの一つで、コンパイル以外にも色々なことができるので、コンパイルもできるけど、他のこと（画像の圧縮など）もできる。
> それを実行するプログラムのことをコンパイラーという（gulp など）
> gulp はタスクランナーの一つで、コンパイル以外にも色々なことができるので、コンパイルもできるけど、他のこと（画像の圧縮など）もできる。

コンパイル以外のこともできるものをコンパイラーと呼ぶのでしょうか？
ちょっと文章全体を見て整えてみてください！

2024-09-20 01:27 UTC, o765cGxHQk commented on note/README.md
> +→ トランスパイルも似たような意味合いであるが、 最新のコードを解析して同じ水準の言語へと変換する。
> → トランスパイルも似たような意味合いであるが、

ここで出てくる「似たような」は何に似ていることを指していますか？
また、TypeScriptからJavaScriptへ変換することはトランスパイルに含みませんか？
TypeScriptのver2.0は2016年リリースです。
これをES2020仕様のJavaScriptに変換することは、変換元は最新ではないのでトランスパイルとは呼びませんか？

2024-09-20 01:27 UTC, o765cGxHQk commented on note/README.md
> +例：React の JSX の構文を babel などを使ってブラウザで動く形にトランスパイルする
いい例ですね🌻

2024-09-20 01:27 UTC, o765cGxHQk commented on note/README.md
> +   ライブラリを管理するツール（例：npm,Yarn）
具体例と使い方も出してくれてありがとうございます！🌷

2024-09-20 12:11 UTC, chiharu1990 commented on note/README.md
> +通常、JavaScript はブラウザ上で動作するプログラミング言語で、OS の機能にアクセスできないが、Node.js は OS の機能にアクセスするプログラムを組むことができる。
こちらNode.jsなどの実行環境で動くことを記述して、JavaScriptランタイムの方と分ける形しました。
OSにアクセスできるという記述は、正確ではなかった（C++でNode.jsの拡張機能を作る必要がある）と参考したページに書いてあったので、そちらの記述はなくしました。

[69a251c](https://github.com/chiharu1990/tspractice/pull/1/commits/69a251c6ba3befbd5e5668b4da657bae2d79e245)

2024-09-20 12:13 UTC, chiharu1990 commented on note/README.md
> +→ JavaScript 実行エンジン（V8 など）と実行基盤（Node.js など）
ありがとうございます！こちら書き方を修正しました！
[4743f4d](https://github.com/chiharu1990/tspractice/pull/1/commits/4743f4d58610338e0cd5d3711714c6fdc953cb08)

2024-09-20 12:15 UTC, chiharu1990 commented on note/README.md
> +ブラウザは JavaScript 実行エンジンがあって（Chrome なら V8,FireFox なら SpiderMonkey など）、これらの実行エンジンにモジュールシステムや API などを加えた JavaScript の実行基盤が JavaScript ランタイム
そもそもAPIってなに・・・ってなって調べたら3種類くらい出てきました・・・
WebAPIかな・・・と思って記述しましたが、ここで言っているAPIって何なんでしょう・・・
[01cd9e2](https://github.com/chiharu1990/tspractice/pull/1/commits/01cd9e2efa59b9e2dfacda5a30cf9eebe4af85e7)

2024-09-20 12:17 UTC, chiharu1990 commented on note/README.md
> +→ gulp はタスクランナーの一つで、コンパイル以外にも色々なことができるので、コンパイルもできるけど、他のこと（画像の圧縮など）もできる。
すいません、最後コミット分けられてなかったので、こちらに書いてありますが、
gulpはタスクランナーであり、コンパイラーとは違うという判断で、記述を削除しました。

[2959841](https://github.com/chiharu1990/tspractice/pull/1/commits/2959841137d066d7e894ee8394a1f3fb40b22965)

2024-09-20 12:18 UTC, chiharu1990 commented on note/README.md
> +→ トランスパイルも似たような意味合いであるが、 最新のコードを解析して同じ水準の言語へと変換する。
トランスパイルとコンパイルについて何が正しいのかわからなくなってきたので、一度整理する時間があったら嬉しいです・・・
調べていくとトランコンパイラとかも出てきて？？？状態となっています・・・
[2959841](https://github.com/chiharu1990/tspractice/pull/1/commits/2959841137d066d7e894ee8394a1f3fb40b22965)

2024-09-24 05:40 UTC, o765cGxHQk commented on note/README.md
> +→ gulp はタスクランナーの一つで、コンパイル以外にも色々なことができるので、コンパイルもできるけど、他のこと（画像の圧縮など）もできる。
> gulp はタスクランナーの一つで、コンパイル以外にも色々なことができる

と、ありますが、gulpは必ずコンパイルするものでしょうか？
gulpの導入されているプロジェクトは必ず何らかをコンパイルしていると見なせますか？

2024-09-24 05:57 UTC, o765cGxHQk requested changes
追記ありがとうございます！！

ねちねちレビューしました！ 🙇 
よろしくお願いします

2024-09-24 05:57 UTC, o765cGxHQk commented on note/README.md
> +アプリケーションを作成するときに必要なパッケージをインストールして使用することができる
インストールするときや、npmを使う上でのコマンドの例をいくつか追記をお願いします。

2024-09-24 05:57 UTC, o765cGxHQk commented on note/README.md
> +例：CSS のフレームワーク TailwindCSS や、React や Vue.js など
これらはどうやってインストールしますか？
また、配布場所はどこでしょうか？

2024-09-24 05:57 UTC, o765cGxHQk commented on note/README.md
> +→ 古い構文にトランスパイルすることで、古いブラウザでも動作するようになる。
文章を書き換えてもらったので、「古い構文」が
どの文脈で出てきたのかわからなくなってしまっていますね。。

コンパイルとトランスパイルについてはお話ししましょう 👀

2024-09-24 05:57 UTC, o765cGxHQk commented on note/README.md
> +ブラウザは JavaScript 実行エンジンがあって（Chrome なら V8,FireFox なら SpiderMonkey など）、これらの実行エンジンにモジュールシステムや Web API？？などを加えた JavaScript の実行基盤が JavaScript ランタイム
ここは口頭でお話ししましょう👀 
（参考URLも知りたいです〜）

2024-09-24 05:57 UTC, o765cGxHQk commented on note/README.md
> +   ライブラリを管理するツール（例：npm,Yarn）
>    ライブラリを管理するツール（例：npm,Yarn）

後述のnpmの項目では「ライブラリ」という言葉はありませんが・・・（姑仕草）

2024-09-24 14:46 UTC, chiharu1990 commented on note/README.md
> +→ gulp はタスクランナーの一つで、コンパイル以外にも色々なことができるので、コンパイルもできるけど、他のこと（画像の圧縮など）もできる。
@o765cGxHQk 
gulpについての記述は無くしたので、コメントでの返信になりますが、
gulpの機能としてsassファイルのコンパイルなどもあるが、それ以外にも自動化であったりファイルの圧縮であったりで使用される場合もあるので、必ず何かをコンパイルしているとは言えないと思いました。

2024-09-24 14:46 UTC, chiharu1990 commented on note/README.md
> +アプリケーションを作成するときに必要なパッケージをインストールして使用することができる
こちら追記しましたので、ご確認お願いいたします！
[2d2be3d]

2024-09-24 14:47 UTC, chiharu1990 commented on note/README.md
> +→ 古い構文にトランスパイルすることで、古いブラウザでも動作するようになる。
口頭でお話した内容ですが、こちらで修正しました！
[e30dc3e](https://github.com/chiharu1990/tspractice/pull/1/commits/e30dc3eac6f347b82a4234f4bdc4918c3add5f4d)

2024-09-24 14:49 UTC, chiharu1990 commented on note/README.md
> +ブラウザは JavaScript 実行エンジンがあって（Chrome なら V8,FireFox なら SpiderMonkey など）、これらの実行エンジンにモジュールシステムや Web API？？などを加えた JavaScript の実行基盤が JavaScript ランタイム
こちらについても口頭でお話した部分ですが、こちらで修正しました！
[e30dc3e](https://github.com/chiharu1990/tspractice/pull/1/commits/e30dc3eac6f347b82a4234f4bdc4918c3add5f4d)

こちらの部分を書くのに参考にしたのは以下のページでした！
https://levtech.jp/media/article/column/detail_459/

2024-09-24 14:51 UTC, chiharu1990 commented on note/README.md
> +   ライブラリを管理するツール（例：npm,Yarn）
一旦ライブラリという言葉は削除してパッケージに修正しましたが、
そうなるとライブラリって何やねん、って話になるのかな、と思いまして調べてみたのですが、
コンパイルとトランスパイル現象に陥っています。。。
（じゃあReactはパッケージなの？ライブラリなの？というような感じで絶賛混乱中です・・・）
[811775c](https://github.com/chiharu1990/tspractice/pull/1/commits/811775c878a9db2d93889db66f4ed66567d2f955)

2024-09-24 14:52 UTC, chiharu1990 commented
@o765cGxHQk 
確認ありがとうございます！
追記できるところは追記しました！
ライブラリとパッケージ（とモジュールも）についてはまた口頭でもお話しできたらと思います！
ご確認よろしくお願いいたします。

2024-09-25 03:10 UTC, o765cGxHQk commented on note/README.md
> +→ gulp はタスクランナーの一つで、コンパイル以外にも色々なことができるので、コンパイルもできるけど、他のこと（画像の圧縮など）もできる。
@chiharu1990 
> gulpの機能としてsassファイルのコンパイルなどもある

また「gulpはコンパイラか？」という話がループしてしまっている感じがします。
gulp の機能はコンパイルですか？
gulp の機能とは何でしょう？

2024-09-25 03:25 UTC, o765cGxHQk requested changes
追記ありがとうございます！

gulp について消してもらったのですが理解を深めるという点でコメントさせていただきました！
npm についてもう少し深掘りしていきましょう！🕳️

2024-09-25 03:25 UTC, o765cGxHQk commented on note/README.md
> +`npm init` で package.json が作られる
`npm init` は何を意味したコマンドですか？
package.json が作られることで何ができますか？

2024-09-25 03:25 UTC, o765cGxHQk commented on note/README.md
> +https://www.npmjs.com/
追加で、パッケージの配布箇所の例として、 async というパッケージが配布されているURLを記載お願いします。

あと、公式サイトは明言できるとよいです。
（情報の最新性や、信頼性に関わるので）

2024-09-25 03:25 UTC, o765cGxHQk commented on note/README.md
> +`npm run start` `npm run dev` `npm run build`
> npm を使うときのコマンド（例）  
> `npm run start` `npm run dev` `npm run build`

この3つはnpmを使うときに必ず存在するコマンドですか？
これらを使用することで何が実現できますか？

2024-09-25 03:53 UTC, o765cGxHQk commented on note/README.md
> +   ライブラリを管理するツール（例：npm,Yarn）
ここは口頭でやりとりしましょう！🐤

2024-09-26 07:26 UTC, chiharu1990 commented on note/README.md
> +→ gulp はタスクランナーの一つで、コンパイル以外にも色々なことができるので、コンパイルもできるけど、他のこと（画像の圧縮など）もできる。
@o765cGxHQk 
gulpの機能
- sassファイルのコンパイル
- 画像やCSSやJavaScriptファイルの圧縮
- ブラウザのリロード
など、Web制作上で必要な作業を自動化することができるもの

参考：https://digitalidentity.co.jp/blog/creative/gulp.html

2024-09-26 08:15 UTC, chiharu1990 commented on note/README.md
> +→ gulp はタスクランナーの一つで、コンパイル以外にも色々なことができるので、コンパイルもできるけど、他のこと（画像の圧縮など）もできる。
memo:
gulp自体には機能がない
gulpだけをインストールしても何もできないが、
gulpにお願いする（gulpfaile.jsに処理を書く）ことで、
さまざまな処理（タスク）ができるようになる

2024-09-27 02:33 UTC, chiharu1990 commented on note/README.md
> +`npm init` で package.json が作られる
こちら追記しました！
[33d817b](https://github.com/chiharu1990/tspractice/pull/1/commits/33d817bef76eda9ed287f71931dd73bb6d149b65)

2024-09-27 02:33 UTC, chiharu1990 commented on note/README.md
> +https://www.npmjs.com/
パッケージの配布場所のURLを追記しました！
[b0e3396](https://github.com/chiharu1990/tspractice/pull/1/commits/b0e3396f47b65d28c05f07bd1d6b0cc7e37f97fa)

2024-09-27 02:34 UTC, chiharu1990 commented on note/README.md
> +`npm run start` `npm run dev` `npm run build`
npmのコマンドについて追記しました！
[cd1b727](https://github.com/chiharu1990/tspractice/pull/1/commits/cd1b727c0df570ea26627279837620efdde0ce21)

2024-09-27 02:35 UTC, chiharu1990 commented
@o765cGxHQk 
返信いただいていた分追記しました！
また、npxについても説明追加しましたので、ご確認お願いいたします！

2024-09-27 04:01 UTC, o765cGxHQk requested changes
ご対応ありがとうございます！
もうひと押しおねがいします！🙏

2024-09-27 04:01 UTC, o765cGxHQk commented on note/README.md
> +ローカルにインストールされていない機能を一時的にインストールして実行するためのコマンド（実行後は削除される）
> パッケージの実行を行うツール。npm のバージョン 5.2.0 より同梱されているコマンド。  

`npx` はツールでしょうか、コマンドでしょうか？
何となく参考にされた情報が古い気がするので、
最新の情報を探してみてください。

> ローカルにインストールされていない機能を一時的にインストールして実行するためのコマンド（実行後は削除される）

TypeScript学習でもnpxコマンドを使われていると思いますが、
ローカルにインストールされていない機能を使っているのでしょうか？

2024-09-27 05:24 UTC, chiharu1990 commented on note/README.md
> +package.json は json 形式で記載されているインストールしたパッケージの情報を保存するファイル。
ありがとうございます！
package.jsonに記載されている情報とメリットについて追記しました！
[fd92116](https://github.com/chiharu1990/tspractice/pull/1/commits/fd92116502f8959a2a30b9048eee34b2a2524573)

2024-09-27 05:25 UTC, chiharu1990 commented on note/README.md
> +`npm run` で package.json の script 欄に定義したコマンドを実行する。script 欄に start や dev などをあらかじめ定義しておき、それを動かすときに使うコマンド。
コマンドについて追記しました！
[3674391](https://github.com/chiharu1990/tspractice/pull/1/commits/3674391bc23b8d2bd99dc67a9c1833481cee77a2)

2024-09-27 05:26 UTC, chiharu1990 commented on note/README.md
> +ローカルにインストールされていない機能を一時的にインストールして実行するためのコマンド（実行後は削除される）
この辺曖昧なのでまた口頭で話せたらと思います・・・！！！

2024-09-27 05:27 UTC, chiharu1990 commented
@o765cGxHQk 
ありがとうございます！
npxの説明以外については追記しましたので、ご確認お願いいたします！！

2024-09-27 06:48 UTC, o765cGxHQk requested changes
もう少し！！お願いします〜〜〜！🙏

2024-09-27 06:48 UTC, o765cGxHQk commented on note/README.md
> +`npm ci` パッケージをクリーンインストールする
ここより後述のパッケージのインストール方法に書いていただいているところで、

> パッケージのインストール方法  
> `npm install <パッケージ名>` の形でインストールする

とありますが、ここで挙げられている `npm install` とは違いがありますか？
クリーンインストールとの違いももう少し詳細にお願いします🙏
（実際はクリーンインストールって◯◯だよね、というやりとりはしないのですが、今回は学習ということで）

2024-09-27 06:48 UTC, o765cGxHQk commented on note/README.md
> +
（意地が悪い聞き方なのですが）
複数人でプロジェクトを開発しないときには役立ちませんか？
ひとりで開発しているときに package.json のメリットはありませんか？

2024-09-27 10:11 UTC, chiharu1990 commented on note/README.md
> +`npm ci` パッケージをクリーンインストールする
クララ会でお話しした部分追記しました！
[db9af77](https://github.com/chiharu1990/tspractice/pull/1/commits/db9af772949483bba9b87bc40bbccd24bec4b3ca)

2024-09-27 10:12 UTC, chiharu1990 commented on note/README.md
> +
クララ会でお話ししたメリットについて追記しました
[db9af77](https://github.com/chiharu1990/tspractice/pull/1/commits/db9af772949483bba9b87bc40bbccd24bec4b3ca)

2024-09-27 10:12 UTC, chiharu1990 commented on note/README.md
> +ローカルにインストールされていない機能を一時的にインストールして実行するためのコマンド（実行後は削除される）
npxについて追記しました！
[db9af77](https://github.com/chiharu1990/tspractice/pull/1/commits/db9af772949483bba9b87bc40bbccd24bec4b3ca)

2024-09-27 10:13 UTC, chiharu1990 commented
クララ会でお話しした部分をまとめましたので、ご確認お願いいたします！

2024-10-04 09:24 UTC, o765cGxHQk approved these changes
ありがとうございます！！
mergeしてOKです！！

2024-10-05 08:15 UTC, chiharu1990 commented
こちらマージします

2024-10-05 08:15 UTC, merged