Gitコマンドについて
chiharu1990/tspractice pull request #11
Opened 2024-10-07 08:33 UTC by chiharu1990

Gitコマンドについてまとめ

2024-10-11 07:27 UTC, o765cGxHQk requested changes
調べてくださりありがとうございます！

コメントした点をご確認お願いします〜！

2024-10-11 07:27 UTC, o765cGxHQk commented on git/README.md
> +`git add -A` 新規追加、更新、削除のファイルが対象になる。ファイル名の指定を省略できる。その場合はリポジトリ内の全てのファイルが対象になる
> `git add .` 変更された全てのファイルをインデックスに追加  
> `git add -A` 新規追加、更新、削除のファイルが対象になる。ファイル名の指定を省略できる。その場合はリポジトリ内の全てのファイルが対象になる  

書いてもらった説明だけ読むと、オプションなしでもすべてのファイルがインデックスされそうですが
実際の挙動はどうでしょうか？

2024-10-11 07:27 UTC, o765cGxHQk commented on git/README.md
> +`git commit --amend` 直前のコミットが修正される
`git commit` だけを実行したらどのような挙動になりますか？

2024-10-11 07:27 UTC, o765cGxHQk commented on git/README.md
> +`git　push origin ブランチ名` 指定したブランチをリモートリポジトリ上の同名のブランチに送信する
現在作業中のブランチをpushする場合はどのようなコマンドになりますか？

2024-10-11 07:27 UTC, o765cGxHQk commented on git/README.md
> +## git add
`git add` でフォルダを追加する場合はどのような挙動になりますか？

2024-10-11 07:27 UTC, o765cGxHQk commented on git/README.md
> +- +を取り消したい場合 → その行を消す
合っています！
`e`を押す前はどのような画面で、どのような挙動ですか？

2024-10-15 05:57 UTC, chiharu1990 commented on git/README.md
> +`git add -A` 新規追加、更新、削除のファイルが対象になる。ファイル名の指定を省略できる。その場合はリポジトリ内の全てのファイルが対象になる
こちら追記しました！
[f2f731c](https://github.com/chiharu1990/tspractice/pull/11/commits/f2f731c888b1111f9f9673255a5a7d191c14e3bd)

2024-10-15 05:57 UTC, chiharu1990 commented on git/README.md
> +`git commit --amend` 直前のコミットが修正される
こちら追記しました！
[f6095dd](https://github.com/chiharu1990/tspractice/pull/11/commits/f6095dde896a88a39251350333c0b5f709690c11)

2024-10-15 05:58 UTC, chiharu1990 commented on git/README.md
> +`git　push origin ブランチ名` 指定したブランチをリモートリポジトリ上の同名のブランチに送信する
こちらも追記しました！
[d1a95a8](https://github.com/chiharu1990/tspractice/pull/11/commits/d1a95a84ebf7f058807fc9a6e1ecdf37352be084)

2024-10-15 05:58 UTC, chiharu1990 commented on git/README.md
> +## git add
こちらも追記しました！
[26d1e4d](https://github.com/chiharu1990/tspractice/pull/11/commits/26d1e4dbf5d1a74e0bcd3f1079cd3dceda942afe)

2024-10-15 05:58 UTC, chiharu1990 commented on git/README.md
> +- +を取り消したい場合 → その行を消す
こちらも追記しました！
[c5ed3c0](https://github.com/chiharu1990/tspractice/pull/11/commits/c5ed3c0ba6b3965dd770c238a5e546f19ec8dede)

2024-10-15 05:58 UTC, chiharu1990 commented
@o765cGxHQk 
確認ありがとうございます！それぞれ追記しましたので、ご確認お願いいたします！

2024-10-15 09:35 UTC, o765cGxHQk commented on git/README.md
> +`git add -A` 新規追加、更新、削除のファイルが対象になる。ファイル名の指定を省略できる。その場合はリポジトリ内の全てのファイルが対象になる
`git add .` と `git add -A` の違いを書いて頂きたかったですー🙏

2024-10-15 09:54 UTC, o765cGxHQk commented on git/README.md
> +`git　push origin ブランチ名` 指定したブランチをリモートリポジトリ上の同名のブランチに送信する
間違ってはいないのですが、もっと簡単に書ける方法があるので↓見て頂きたいです！
（扇状的なタイトルはどうかと思うのですが公式ドキュメントの引用があり・・・）
https://qiita.com/Takao_/items/44d2aa23d6b1ab22a53a

2024-10-15 09:55 UTC, o765cGxHQk commented on git/README.md
> +- +を取り消したい場合 → その行を消す
ありがとうございます！
こういった挙動（使う側がyとかnとか入力する）はちょくちょくあるので、
何と呼ぶか調べてほしいです！

2024-10-15 09:56 UTC, o765cGxHQk requested changes
対応ありがとうございます！
コメントに返信をしましたので、ご確認をお願いします。

2024-10-15 13:51 UTC, chiharu1990 commented on git/README.md
> +`git add -A` 新規追加、更新、削除のファイルが対象になる。ファイル名の指定を省略できる。その場合はリポジトリ内の全てのファイルが対象になる
追記しました！
`git add .` はその階層のファイルをまとめてインデックスに登録するコマンドで、
`git add -A`はリポジトリ内のすべてのファイルが対象になるコマンドという認識です！
[440917f](https://github.com/chiharu1990/tspractice/pull/11/commits/440917fd8b1e6425be92b222f34216c869247c0c)

2024-10-15 13:52 UTC, chiharu1990 commented on git/README.md
> +`git　push origin ブランチ名` 指定したブランチをリモートリポジトリ上の同名のブランチに送信する
ありがとうございます！追記しました！（こっちの方が100倍楽ですね・・・）
[ce5b268](https://github.com/chiharu1990/tspractice/pull/11/commits/ce5b268df9cc2667d6e0663431aea3467a8a9895)

2024-10-15 13:52 UTC, chiharu1990 commented on git/README.md
> +- +を取り消したい場合 → その行を消す
自信ないですが追記しました・・・間違っていたらクララ会でお願いします・・・
[04df374](https://github.com/chiharu1990/tspractice/pull/11/commits/04df374664dd2e2102973f0dddb4c9a26fb18fc0)

2024-10-15 13:53 UTC, chiharu1990 commented
ありがとうございます！追記しましたので、ご確認お願い致します！

2024-10-17 07:03 UTC, o765cGxHQk requested changes
追記ありがとうございます！

コメントしました！

2024-10-17 07:03 UTC, o765cGxHQk commented on git/README.md
> +`git add`はファイルの中身をインデックスに追加するコマンド
> `git add`はファイルの中身をインデックスに追加するコマンド  

この説明がふるまいの説明として適切かな〜・・というのを見直して欲しいです🍠

2024-10-17 07:04 UTC, o765cGxHQk commented on git/README.md
> +`git　push origin ブランチ名` 指定したブランチをリモートリポジトリ上の同名のブランチに送信する
ありがとうございます！
追加なのですが、
何もオプションをつけずに `git push` したときの挙動も調べておいてほしいです〜 👀

2024-10-17 07:04 UTC, o765cGxHQk commented on git/README.md
> +- +を取り消したい場合 → その行を消す
伝え方が悪かったと思うので、お話ししましょう〜！

2024-10-17 10:43 UTC, chiharu1990 commented on git/README.md
> +`git　push origin ブランチ名` 指定したブランチをリモートリポジトリ上の同名のブランチに送信する
`git push`した時の挙動について追記しました！
[cae3f14](https://github.com/chiharu1990/tspractice/pull/11/commits/cae3f14f640476360c604873fb73ce9b781676a6)

2024-10-17 10:44 UTC, chiharu1990 commented on git/README.md
> +- +を取り消したい場合 → その行を消す
こちらクララ会で修正しました！
[789469a](https://github.com/chiharu1990/tspractice/pull/11/commits/789469a9c5cd9a34397e98c0521db461693b8be2)

2024-10-17 10:44 UTC, chiharu1990 commented on git/README.md
> +`git add`はファイルの中身をインデックスに追加するコマンド
こちらもクララ会で追記しました！
[789469a](https://github.com/chiharu1990/tspractice/pull/11/commits/789469a9c5cd9a34397e98c0521db461693b8be2)

2024-10-17 10:44 UTC, chiharu1990 commented
ありがとうございます！！
クララ会で追記した分と、`git push`した時の挙動について追記しましたので、ご確認お願い致します！

2024-10-18 02:17 UTC, o765cGxHQk requested changes
追記ありがとうございます！
もう一声おねがいします〜！

2024-10-18 02:17 UTC, o765cGxHQk commented on git/README.md
> +上流ブランチの設定は`git branch -u <リモート追跡ブランチ> <ローカルブランチ>`で設定できる　　
> 上流ブランチの設定は`git branch -u <リモート追跡ブランチ> <ローカルブランチ>`で設定できる　　

このコマンドが間違っている気がするのでもう一度調べていただけますか？

2024-10-18 02:17 UTC, o765cGxHQk commented on git/README.md
> +`git push -u origin <ローカルブランチ>`とすることで、push時に上流ブランチを設定することができる
💭 細かいのですが、これだと毎回 `-u` するべきに読めます。
push の際に `-u` を設定するのであれば、いつ `-u` をつけるべきでしょうか？
（あと、`-u` の省略形じゃないコマンドも記載されているとうれしいです！）

2024-10-18 10:46 UTC, chiharu1990 commented on git/README.md
> +上流ブランチの設定は`git branch -u <リモート追跡ブランチ> <ローカルブランチ>`で設定できる　　
上流ブランチの設定方法について追記しました！
[0787631](https://github.com/chiharu1990/tspractice/pull/11/commits/0787631a323d3d500dc254a35d1d564cc494015b)

2024-10-18 10:46 UTC, chiharu1990 commented on git/README.md
> +`git push -u origin <ローカルブランチ>`とすることで、push時に上流ブランチを設定することができる
pushの時に`-u`を使う時と、`-u`の省略形じゃないコマンドを追記しました！
[0787631](https://github.com/chiharu1990/tspractice/pull/11/commits/0787631a323d3d500dc254a35d1d564cc494015b)

2024-10-21 03:45 UTC, o765cGxHQk approved these changes
修正ありがとうございました！
こちらmergeしてください！🙆‍♀️

2024-10-22 02:35 UTC, merged