３章の振り返り
chiharu1990/tspractice pull request #24
Opened 2024-10-18 14:15 UTC by chiharu1990

振り返りの演習問題を教科書を見ずに一度回答して、その後わからなかった部分を教科書を見ながら追記しました！
オブジェクトの操作のドリルについては、すべて期待通り実行できたと思うので、レビューお願い致します！

2024-10-21 04:02 UTC, o765cGxHQk requested changes
早速取り掛かっていただいてありがとうございます！

コメントしましたので、ご確認をお願いいたします🌹

2024-10-21 04:02 UTC, o765cGxHQk commented on src/clara/section3/drill6.ts
> +}
🙆 こちらも回答としては正解です！

追加課題として2点お願いします。
1.  [drill5.ts](https://github.com/chiharu1990/tspractice/pull/24/files#diff-7358dd11f2f849a21b573fdf5ff6f351c487cbfddae0dd0fd3a852513a7b6072) へのコメントと同じく、よりすっきり書いてみてください。
2. ブルーベリー本に出てきた方法で、unit がもっとすっきり書けるように挑戦してください。

2がどうしてもわからない場合は、ブルーベリー本の 3.6.5 を読み返してみてください。

2024-10-22 04:01 UTC, chiharu1990 commented on src/clara/section3/README.md
> +- オブジェクトリテラルの中のプロパティの定義は`プロパティ名: 式`と書く
こちらクララ会でお願いします！

2024-10-22 04:02 UTC, chiharu1990 commented on src/clara/section3/drill1.ts
> +const result = arr1;
こちら修正しました！
[d96a540](https://github.com/chiharu1990/tspractice/pull/24/commits/d96a540b07a1be6d9cfab8b87226973a1c48761c)

2024-10-22 04:02 UTC, chiharu1990 commented on src/clara/section3/drill3.ts
> +const result = member;
こちらも修正しました！
[1c833d1](https://github.com/chiharu1990/tspractice/pull/24/commits/1c833d1508dedad9ed1dbc4940600e2ddcf59561)

2024-10-22 04:03 UTC, chiharu1990 commented on src/clara/section3/drill5.ts
> +};
こちらも修正しました！
[e6b6ac4](https://github.com/chiharu1990/tspractice/pull/24/commits/e6b6ac40de5e860dce1037a6ca2842aa97ad12fd)

2024-10-22 04:03 UTC, chiharu1990 commented on src/clara/section3/drill6.ts
> +}
こちらも修正しました！
[3acb91f](https://github.com/chiharu1990/tspractice/pull/24/commits/3acb91fce67fa47b3c6448e9f4cd62ac28eca111)

2024-10-22 04:03 UTC, chiharu1990 commented
@o765cGxHQk 
確認ありがとうございます！！
コメントでいただいていた部分修正しましたので、ご確認お願いいたします！

2024-10-22 05:38 UTC, o765cGxHQk commented on src/clara/section3/drill1.ts
> +const result = arr1;
🙆‍♀️💯

2024-10-22 05:39 UTC, o765cGxHQk commented on src/clara/section3/drill5.ts
> +};
🙆‍♀️💯

2024-10-22 05:39 UTC, o765cGxHQk commented on src/clara/section3/drill6.ts
> +}
🙆‍♀️💯

2024-10-22 05:43 UTC, o765cGxHQk requested changes
おおむねいい感じです！
あともう一息お願いします🤲

2024-10-22 05:43 UTC, o765cGxHQk commented on src/clara/section3/drill3.ts
> +result.stageName = "TY";
もう1行減らせるので挑戦してみてください！

わからない場合は、 3.1.5 を読み直してみてください。

2024-10-22 06:42 UTC, chiharu1990 commented on src/clara/section3/drill3.ts
> +result.stageName = "TY";
ありがとうございます！
読み直して修正しました！！
[106be77](https://github.com/chiharu1990/tspractice/pull/24/commits/106be7721682b1cafe9477ea7761b109299ee7fd)

2024-10-22 07:57 UTC, o765cGxHQk commented on src/clara/section3/drill3.ts
> +result.stageName = "TY";
💯🙆

2024-10-24 06:52 UTC, o765cGxHQk approved these changes
ご対応ありがとうございました！
マージお願いします！

（オブジェクトリテラルを迷わせてすみませんでした）

2024-10-24 08:02 UTC, chiharu1990 commented
こちらマージします！

2024-10-24 08:02 UTC, merged