第2弾 Gitコマンドについて
chiharu1990/tspractice pull request #32
Opened 2024-10-30 11:11 UTC by chiharu1990

以下のGitコマンドについてまとめました。

- git merge
- git pull
- git rebase
- git reset
- git revert
- git stash
- git status

2024-10-30 11:11 UTC, chiharu1990 commented
@o765cGxHQk 
Gitコマンドについてまとめましたので、ご確認お願いします！

2024-10-31 03:43 UTC, o765cGxHQk requested changes
ちくちくコメントしましたのでご確認お願いします！🙏

2024-10-31 03:43 UTC, o765cGxHQk commented on git/README.md
> +`git merge main` とすることで、mainブランチの変更を作業用のブランチに取り込むことができる。
この挙動は rebase と違いがありますか？

2024-10-31 03:43 UTC, o765cGxHQk commented on git/README.md
> +1. mainブランチにチェックアウト
> チェックアウト

ここで使われているチェックアウトはコマンド(git checkout)として読むと正しいのですが、
言葉として読むと違和感があります。
(Gitのような履歴管理システムでは、チェックアウトは管理元から履歴を取り出すことを指すため)
(意味は通じるんですが意識的に言葉を使ってほしさがあり・・)

2024-10-31 03:43 UTC, o765cGxHQk commented on git/README.md
> +rebaseは、1つのブランチから別のブランチへの変更を統合する
rebaseの説明として正しくはないです。
たとえば、rebase を使うことですでにコミットしたコミットメッセージの修正や、
コミットの削除などが行えます。
もう一度調べてみてください。

2024-10-31 03:43 UTC, o765cGxHQk commented on git/README.md
> +2. `git rebase <リベース先のブランチ名>` （例の場合だと`git rebase main`）
具体例としてはおおむね正しいのですが、口頭確認しておきたいです👀

2024-10-31 03:43 UTC, o765cGxHQk commented on git/README.md
> +特定の時点までファイルを巻き戻す
オプションをつけた場合の説明になっている気がします。
単純に `git reset` だけ実行した場合はどうなりますか？

2024-10-31 03:43 UTC, o765cGxHQk commented on git/README.md
> +revertは新たにコミットをするコマンドで、コミット履歴を改変することはない。
> revertは新たにコミットをするコマンドで、コミット履歴を改変することはない。

では、履歴を改変するコマンドもあります・・？🤔

2024-10-31 03:43 UTC, o765cGxHQk commented on git/README.md
> +`git stash pop stash@{n}` スタッシュの復活と削除を同時に行う
たくさんオプションを書いてくれて良いと思います！🙆‍♀️ 

`git stash apply` のようにstashの番号を指定しない場合はどういった挙動をしますか？

2024-10-31 03:43 UTC, o765cGxHQk commented on git/README.md
> +## git status
💯

2024-10-31 03:43 UTC, o765cGxHQk commented on git/README.md
> +1. `git reflog`を使って該当のコミットIDを調べる
reflog以外ではコミットIDは調べられませんか？

2024-11-01 13:40 UTC, chiharu1990 commented on git/README.md
> +`git merge main` とすることで、mainブランチの変更を作業用のブランチに取り込むことができる。
mergeとrebaseについて追記しました！
[54d4f71](https://github.com/chiharu1990/tspractice/pull/32/commits/54d4f710abb1d0460d3c647a0af1bfb1795e2613)

2024-11-01 13:40 UTC, chiharu1990 commented on git/README.md
> +1. mainブランチにチェックアウト
こちらで修正しました！
[54d4f71](https://github.com/chiharu1990/tspractice/pull/32/commits/54d4f710abb1d0460d3c647a0af1bfb1795e2613)

2024-11-01 13:40 UTC, chiharu1990 commented on git/README.md
> +rebaseは、1つのブランチから別のブランチへの変更を統合する
mergeとrebaseについて追記しました！
[54d4f71](https://github.com/chiharu1990/tspractice/pull/32/commits/54d4f710abb1d0460d3c647a0af1bfb1795e2613)

2024-11-01 13:41 UTC, chiharu1990 commented on git/README.md
> +2. `git rebase <リベース先のブランチ名>` （例の場合だと`git rebase main`）
こちらも修正しました！
[54d4f71](https://github.com/chiharu1990/tspractice/pull/32/commits/54d4f710abb1d0460d3c647a0af1bfb1795e2613)

2024-11-01 13:41 UTC, chiharu1990 commented on git/README.md
> +特定の時点までファイルを巻き戻す
resetについて追記しました！
[c8f8def](https://github.com/chiharu1990/tspractice/pull/32/commits/c8f8defabd119c42d2b4648875fee276048ff7d5)

2024-11-01 13:42 UTC, chiharu1990 commented on git/README.md
> +revertは新たにコミットをするコマンドで、コミット履歴を改変することはない。
履歴を改変するコマンドについて追記しました！
[dc5723a](https://github.com/chiharu1990/tspractice/pull/32/commits/dc5723a7972f62c9c67716c8b375c73d19062fe0)

2024-11-01 13:42 UTC, chiharu1990 commented on git/README.md
> +`git stash pop stash@{n}` スタッシュの復活と削除を同時に行う
こちらの挙動も追記しました！
[11a89a5](https://github.com/chiharu1990/tspractice/pull/32/commits/11a89a54c458d020aeb6754aad7f0d29b606102e)

2024-11-01 13:43 UTC, chiharu1990 commented on git/README.md
> +1. `git reflog`を使って該当のコミットIDを調べる
`reflog`以外にコミットIDを調べるコマンドを追記しました！
[1fdd221](https://github.com/chiharu1990/tspractice/pull/32/commits/1fdd221a29c524efde58ad8ac70b1ad95916ef08)

2024-11-01 13:44 UTC, chiharu1990 commented
@o765cGxHQk 
コメントいただいた内容について追記しましたので、ご確認お願いいたします！

2024-11-06 07:32 UTC, o765cGxHQk requested changes
追記ありがとうございます！
もうひと押しお願いいたします！

2024-11-06 07:32 UTC, o765cGxHQk commented on git/README.md
> +rebaseは、コミットを作り直して、ログをきれいにするためのコマンド
rebaseはコミットを作り直す機能という点はその通りなのですが、
ログをきれいにするものとするのは違和感があります。
gitに提供されている機能(コミットの作り直し)と、使う側の目的(ログをきれいにしたい)が混在している気がします。

2024-11-06 07:32 UTC, o765cGxHQk commented on git/README.md
>  ただし、rebaseをするとコミットIDが書き換わる（新たなコミットとなる）ので、すでにリモートリポジトリにpushしたコミットをリベースしてはいけない。
> すでにリモートリポジトリにpushしたコミットをリベースしてはいけない。

レビュアーに対して気をつけた方がいいことではありますが、
リベースしてはいけないわけではないです。
（rebaseしたコミットをpushする方法も提供されているので）

2024-11-06 07:32 UTC, o765cGxHQk commented on git/README.md
> +`git merge main` とすることで、mainブランチの変更を作業用のブランチに取り込むことができる。
よいと思います！🙆

[nits]
コミットメッセージにはmergeとrebaseについて編集した旨書かれているのですが、
実際は`git pull`の欄にも誤字修正がありますよね。
コミットメッセージの内容に則していない変更は含まないように意識しましょう！

2024-11-06 07:32 UTC, o765cGxHQk commented on git/README.md
> +特定の時点までファイルを巻き戻す
オプションをつけずに`git reset`だけ実行した場合、特定の時点に戻りますか？

2024-11-06 07:32 UTC, o765cGxHQk commented on git/README.md
> +revertは新たにコミットをするコマンドで、コミット履歴を改変することはない。
良いと思います！

💭 履歴を改変する／しないのそれぞれの使い所を想像してもらえるとよいかな〜と思います。

2024-11-06 13:00 UTC, chiharu1990 commented on git/README.md
>  ただし、rebaseをするとコミットIDが書き換わる（新たなコミットとなる）ので、すでにリモートリポジトリにpushしたコミットをリベースしてはいけない。
ありがとうございます！
IDが書き換わることで起こりうる問題について追記しました！
[decac68](https://github.com/chiharu1990/tspractice/pull/32/commits/decac685e274581e3f0bdf85d17372eb4478bdf3)

2024-11-06 13:02 UTC, chiharu1990 commented on git/README.md
> +revertは新たにコミットをするコマンドで、コミット履歴を改変することはない。
revertの使い所について追記しました！
（resetについてはresetの方に詳しく書いてあるので、省きました）
[711cd05](https://github.com/chiharu1990/tspractice/pull/32/commits/711cd05372a135bb7368d6afe892d26c0d11d6d3)

2024-11-06 13:04 UTC, chiharu1990 commented on git/README.md
> +`git merge main` とすることで、mainブランチの変更を作業用のブランチに取り込むことができる。
ありがとうございます！ついでの修正気をつけます！

2024-11-07 04:18 UTC, o765cGxHQk commented on git/README.md
> +revertは新たにコミットをするコマンドで、コミット履歴を改変することはない。
よいと思います〜！🙆
今更なのですがコマンド名が`git-revert`とハイフンが入っているので直していただけると・・👀

2024-11-07 04:20 UTC, o765cGxHQk commented on git/README.md
> +特定の時点までファイルを巻き戻す
これはお話ししましょう〜

2024-11-07 04:23 UTC, o765cGxHQk requested changes
追記ありがとうございます！
（勉強になる〜〜〜）

あと細かい点と、すこし口頭でお話しできればと思います！

2024-11-07 04:23 UTC, o765cGxHQk commented on git/README.md
> +`git-revert`は新たにコミットをするコマンドで、`git reset`のようにコミット履歴を改変することはない。
コマンドについて書かれているのであれば、ハイフンの削除お願いします〜

```suggestion
`git revert`は新たにコミットをするコマンドで、`git reset`のようにコミット履歴を改変することはない。  
```

2024-11-07 05:31 UTC, chiharu1990 commented on git/README.md
> +`git-revert`は新たにコミットをするコマンドで、`git reset`のようにコミット履歴を改変することはない。
誤字修正しました！！
[c16edd5](https://github.com/chiharu1990/tspractice/pull/32/commits/c16edd501e28a3418ef5bcd2d1810468e7bc8c25)

2024-11-07 08:38 UTC, chiharu1990 commented on git/README.md
> +特定の時点までファイルを巻き戻す
こちらまとめ直しました！
[9ac0e4e](https://github.com/chiharu1990/tspractice/pull/32/commits/9ac0e4efd94e365af665aaa50581dd9e53f8a8fe)

2024-11-07 13:03 UTC, merged