４章の復習
chiharu1990/tspractice pull request #36
Opened 2024-11-03 11:27 UTC by chiharu1990

4章の復習をしました
- 返り値の型注釈を省略した場合はどのような挙動になるか (省略しなかった場合とのメリット・デメリットを比較しながら説明すること)
- コールバック関数の具体例を1つ書くこと
- 引数に2つの数値を受け取り、それを足し合わせた数値を返す関数を関数宣言を書くこと (引数・戻り値に型注釈をつけること)
- 上記と同じ関数を、関数式として書くこと
- 上記と同じ関数を、アロー関数式として書くこと
- コールシグネチャとは何か (具体例を含めて回答すること)
- ジェネリクスとは何か (具体例を含めて回答すること)
- オプショナル引数を使った関数の具体例を1つ書くこと

2024-11-06 04:53 UTC, o765cGxHQk requested changes
回答おつかれさまでした！
いくつかコメントを書いたのでご確認お願いします〜！

2024-11-06 04:53 UTC, o765cGxHQk commented on src/clara/section4/README.md
> +```
関数宣言と関数式が反対になっています👀

2024-11-06 04:53 UTC, o765cGxHQk commented on src/clara/section4/README.md
> +`変数名?: 型`という構文を用いる
ここは`引数名`のことを意図していましたか？
```suggestion
`引数名?: 型`という構文を用いる  
```

2024-11-06 04:53 UTC, o765cGxHQk commented on src/clara/section4/README.md
> +const sum = (num1: number, num2?: number) : number[] => {
オプショナル引数の例としては合っているのですが、
配列を作る関数名が `sum` なのは実体に則していないのが気になりました。

2024-11-06 04:53 UTC, o765cGxHQk commented on src/clara/section4/README.md
> +```
コールバック関数の例としてmap関数は正しいです！

ただ、mapメソッドは新しい配列を返り値とするメソッドなので、
返り値を使わない場合は非推奨となっています。

ref.
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/map
```suggestion
const arr: number[] = [1,2,3,4,5];
arr.map((elm: number) => {
  return elm;
});
console.log(arr); // => [1,2,3,4,5]
```

2024-11-06 10:47 UTC, chiharu1990 commented on src/clara/section4/README.md
> +`変数名?: 型`という構文を用いる
ありがとうございます！！書き間違いでした！
修正しました！
[3e80d58](https://github.com/chiharu1990/tspractice/pull/36/commits/3e80d5879df04240926acd023e4003a2eb0e6fe4)

2024-11-06 10:47 UTC, chiharu1990 commented on src/clara/section4/README.md
> +const sum = (num1: number, num2?: number) : number[] => {
こちら関数名を修正しました！
[24adc6d](https://github.com/chiharu1990/tspractice/pull/36/commits/24adc6d1bd282c3f356aa9e0d0ecdbf98b0efce9)

2024-11-06 10:48 UTC, chiharu1990 commented on src/clara/section4/README.md
> +```
ありがとうございます！
修正しました！
[3354ba2](https://github.com/chiharu1990/tspractice/pull/36/commits/3354ba24261a0dffd75cca183f8268ed4b4ede78)

2024-11-07 04:06 UTC, o765cGxHQk requested changes
ご対応ありがとうございます！
細かい点ですが追加でお願いします〜！

2024-11-07 04:06 UTC, o765cGxHQk commented on src/clara/section4/README.md
> +console.log(sum(1)); // [ 1 ]
🍠
こういった処理はこうも書けます。

```TypeScript
const returnNumberArray = (num1: number, num2?: number): number[] => {
  const arr: number[] = [];

  // num2の有無に関わらずnum1はpushするので、ここでpush
  arr.push(num1);

  // num2の有無による分岐を書く
  if (num2 !== undefined) {
    arr.push(num2);
  }

  return arr;
};

console.log(returnNumberArray(1)); // [ 1 ]
console.log(returnNumberArray(1,6)); // [1, 6] 
```

2024-11-07 06:01 UTC, chiharu1990 commented on src/clara/section4/README.md
> +デフォルト値を指定する場合は、`変数名: 型 = 式`という構文を用いる
修正しました！！（テキストでは変数名になっていたのですが、引数名でもわかると判断しました！）
[954cda5](https://github.com/chiharu1990/tspractice/pull/36/commits/954cda5433295e9b75e214dcf13d7005bc43b985)

2024-11-07 06:01 UTC, chiharu1990 commented on src/clara/section4/README.md
> +console.log(sum(1)); // [ 1 ]
修正しました！見落とし気をつけます！
[ae97db1](https://github.com/chiharu1990/tspractice/pull/36/commits/ae97db19af577436bc27367961267626967914cb)

2024-11-07 06:03 UTC, chiharu1990 commented on src/clara/section4/README.md
> +console.log(sum(1,3)); // [ 1, 3 ]
こちらも関数名変更しました！
オプショナル引数の例題関数なので、関数名は`returnNumberArray`統一にしました！
[d871ae6](https://github.com/chiharu1990/tspractice/pull/36/commits/d871ae640442fb042cdf360f863b3d92b3638dda)

2024-11-07 06:03 UTC, chiharu1990 commented on src/clara/section4/README.md
> +console.log(sum(1)); // [ 1 ]
ありがとうございます！
別の書き方として追記させてもらいました！！
[ffda092](https://github.com/chiharu1990/tspractice/pull/36/commits/ffda092b325f874aae46d40e1aee11ae16bf8b16)

2024-11-07 11:29 UTC, o765cGxHQk requested changes
すご〜〜〜く細かくて申し訳ないんですが1点だけご確認お願いします！

2024-11-07 11:29 UTC, o765cGxHQk commented on src/clara/section4/README.md
> +```
めちゃくちゃ細かいんですが、returnするように書き換えていただいたので
console.logがなくなったため、mapメソッドで何をしたかの説明と関数が噛み合わなくなっています🙏

2024-11-29 06:22 UTC, o765cGxHQk approved these changes
長らく寝かせてしまいすみません！
こちらApproveです！👍

2024-12-03 13:20 UTC, merged