async/await 課題
chiharu1990/tspractice pull request #47
Opened 2024-12-14 14:19 UTC by chiharu1990

- await式とは何か
- Promiseとは何か (どのような利点があるかも説明すること。また、Promiseを使ったコード例を1つ書くこと)
- 次のコードの問題点を回答すること (また、改善する方法も回答すること)
```
try {
  setTimeout(() => {
    throw new Error("エラー");
  }, 0);
} catch (error) {
  console.error(error);
}
```
- Async Functionとは何か
- 次のコードをsleepに対応するコードを記入すること
```
await sleep(1000);
console.log("1秒後に実行する"); // 上記のsleep関数で1秒経過した後に、こちらのconsole.log()を実行する
```
- https://httpbin.org/json にfetch APIを使ってリクエストし、fetch APIでエラーが発生した際には「通信でエラーが発生しました。しばらく経ってから再度お試しください」というエラーをConsoleに出力するコードを書く

2024-12-14 14:19 UTC, chiharu1990 commented
@o765cGxHQk 
こちらお手隙でご確認お願いいたします！
初見はほぼわからず、調べながらの回答となります・・・

2024-12-17 09:36 UTC, o765cGxHQk requested changes
むずかしいところですがご確認おねがいしますー！

2024-12-17 09:36 UTC, o765cGxHQk commented on src/clara/async-await/README.md
> +example();
[ask]
> let result = await someAsyncFunction();

ここではなぜ `let` を使用しましたか？

2024-12-17 09:36 UTC, o765cGxHQk commented on src/clara/async-await/README.md
> +      console.log(3);
[ask]
以下はなんの用途に入れましたか？
```
console.log(3);
```

2024-12-17 09:36 UTC, o765cGxHQk commented on src/clara/async-await/README.md
> +});
Promiseオブジェクトに対するチェーンは、`.catch()` が必須です。

2024-12-17 09:36 UTC, o765cGxHQk commented on src/clara/async-await/README.md
> +```
`await`式の後に`console.log()`を表示するのが今回の課題なので、
以下の順番は変えずにコードを書いてください。
```
await sleep(1000);
console.log("1秒後に実行する");
```

2024-12-17 09:36 UTC, o765cGxHQk commented on src/clara/async-await/README.md
> +```
これをawait/asyncを用いてコードを書けますか？

2024-12-17 13:22 UTC, chiharu1990 commented on src/clara/async-await/README.md
> +await 式は主に非同期関数内で使われる構文で、Promise が解決するのを待つために使う。await 式を使うことで、非同期処理が同期処理のように上から下へと順番に実行するような処理順で書くことができる。
@o765cGxHQk 
ありがとうございます！修正しました！！
[ed71166](https://github.com/chiharu1990/tspractice/pull/47/commits/ed71166edb32e81f600038d8e1b543fac49d8bda)

2024-12-17 13:24 UTC, chiharu1990 commented on src/clara/async-await/README.md
> +example();
@o765cGxHQk 
chatGPT先輩に聞きながらやっていたので、その記述がそのままになっていました。。。
letである必要はないので、constに修正しました。
[665f3e6](https://github.com/chiharu1990/tspractice/pull/47/commits/665f3e670b1325ccb6fc1bda011ac9138fe83a37)

2024-12-17 13:25 UTC, chiharu1990 commented on src/clara/async-await/README.md
> +      console.log(3);
@o765cGxHQk 
これも、いろいろな資料を見ながらやっていて、ちゃんと1秒後に実行されているよね？という確認で入れていただけでした。
不要な記述だと思ったので、削除しました！
[ce18191](https://github.com/chiharu1990/tspractice/pull/47/commits/ce1819146fc7bab959c47457bcc4d7872f158927)

2024-12-17 13:25 UTC, chiharu1990 commented on src/clara/async-await/README.md
> +});
@o765cGxHQk 
catchメソッドを追記しました！
[6e5df20](https://github.com/chiharu1990/tspractice/pull/47/commits/6e5df20d29185fda8d8b4fa59f4d990dda26ab94)

2024-12-17 13:26 UTC, chiharu1990 commented on src/clara/async-await/README.md
> +```
@o765cGxHQk 
console.logの位置を修正しました！
[a66b31a](https://github.com/chiharu1990/tspractice/pull/47/commits/a66b31aa8d7c5f5a6071a12bb37f146508bfcfd8)

2024-12-17 13:26 UTC, chiharu1990 commented on src/clara/async-await/README.md
> +```
@o765cGxHQk 
async / awaitを用いて書き直しました！
[b6320d5](https://github.com/chiharu1990/tspractice/pull/47/commits/b6320d5de39c4958b9727c4ea183227f27f454b8)

2024-12-18 00:56 UTC, o765cGxHQk commented on src/clara/async-await/README.md
> +example();
chatGPTに聞きながらとのことで、ちょっと掘り下げてお聞きしますね。

- `Promise.resolve()` のような構文を何と呼ぶでしょうか？
- この構文を用いたときのメリットは何でしょうか？
- この構文を用いずにPromiseオブジェクトのresolveを返すコードを書けますか？

2024-12-18 00:57 UTC, o765cGxHQk commented on src/clara/async-await/README.md
> +      console.log(3);
OKです！

2024-12-18 00:57 UTC, o765cGxHQk commented on src/clara/async-await/README.md
> +});
OKです！
ここも資料添付しておきます。

ref.
https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Using_promises

2024-12-18 01:02 UTC, o765cGxHQk commented on src/clara/async-await/README.md
> +```
この記述ですと、非同期処理(`fetch()`)に続く処理が`.then()`, `.catch()`で実行されており、
await式で書いたというよりも、Promiseオブジェクトのチェーンメソッドで処理されています。
チェーンメソッドを用いずに書いてみてください。

2024-12-18 12:39 UTC, chiharu1990 commented on src/clara/async-await/README.md
> +example();
@o765cGxHQk 
糖衣構文について追記しました
[a957d84](https://github.com/chiharu1990/tspractice/pull/47/commits/a957d84aa8f97f4ec9248e15a3a82a562a6c19fd)

2024-12-24 09:02 UTC, o765cGxHQk approved these changes
1点コメントしましたがimoなので、よさそうです！

2024-12-25 13:26 UTC, chiharu1990 commented
@o765cGxHQk 
ありがとうございます！マージします！

2024-12-25 13:26 UTC, merged